### PR TITLE
Remove sh dependency

### PR DESCRIPTION
**Pull request by felipemfp**
Hi, I have removed the sh dependency.

I only test it on my Ubuntu and Windows 10 with Git, so if you have problems with that, let me know, so I can try fix.

`sh` is currently only supported on linux and osx.

### CODE REVIEW

**Comment by alephmelo** [comment]
That is great, man!

I'll do some testing later and I'll get back to you. 

I choose `sh` over `subprocess` because `sh` is way better in readability and usability. But I guess subprocess can do the trick as well.

Thank you for your PR, I really appreciate. 

👍 

EDIT 1:
I ran your modifications and I found one problem:
```
$ watchman check -s git
alephmelo.github.io       is on branch: source
bookish-waddle            is on branch: master
fatal: Not a git repository: './bottle/.git'
...
```
Earlier, using sh this 'not a git or hg repo' was handled by the exception, not printing anything and just continuing for the next folder.

Can you take a look? Thanks! o/

**Comment by felipemfp** [comment]
I'll check this.

I was expecting the subprocess raise a CalledProcessError, so it can be handled by the try... except.

**Comment by felipemfp** [comment]
Hey!

I've commited a fix.

**Comment by alephmelo** [comment]
Nice, Felipe!

Gonna take a closer look later on.

Thanks, man.

**Comment by alephmelo** [comment]
Merged #2 

Thank you, bro! :clap: :clap:

**Pull request merged**
